# Generated by Django 3.0.5 on 2020-05-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=20, verbose_name='Banco')),
                ('numero', models.IntegerField(verbose_name='Numero de la tarjeta')),
                ('fecha', models.DateField(verbose_name='Caducidad')),
                ('digitos', models.IntegerField(verbose_name='Clave 3 digitos')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=15, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=15, verbose_name='Apellido materno')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('calle_numero', models.CharField(max_length=40, verbose_name='Calle y numero')),
                ('colonia', models.CharField(max_length=20, verbose_name='Colonia')),
                ('delegacion', models.CharField(max_length=15, verbose_name='Delegación')),
                ('estado', models.CharField(max_length=15, verbose_name='Estado')),
                ('pais', models.CharField(max_length=15, verbose_name='País')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Calle y numero')),
            ],
        ),
    ]
