# Generated by Django 3.0.5 on 2020-05-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_venta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre del propietario'),
        ),
    ]
