# Generated by Django 3.0.5 on 2020-05-02 20:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('edad', models.IntegerField()),
                ('pais', models.CharField(max_length=20, verbose_name='País')),
                ('comentario', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
