# Generated by Django 3.0.5 on 2020-04-28 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0002_auto_20200427_1811'),
        ('discos', '0002_auto_20200427_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='artista.Artista'),
        ),
    ]
